# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croplet', '0003_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
